import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Ticket } from '../types';
import { ticketsAPI } from '../utils/api';
import toast from 'react-hot-toast';
import StatusBadge from '../components/StatusBadge';
import { ArrowLeft, Sparkles } from 'lucide-react';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';

const TicketDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [ticket, setTicket] = useState<Ticket | null>(null);
  const [loading, setLoading] = useState(true);
  const [aiLoading, setAiLoading] = useState(false);

  const fetchTicket = async () => {
    if (!id) return;
    try {
      // Fetch all and find the one (since no GET single implemented)
      const allTickets: Ticket[] = await ticketsAPI.getTickets();
      const found = allTickets.find((t) => t.id === parseInt(id));
      if (found) {
        setTicket(found);
      } else {
        toast.error('Ticket not found');
        navigate('/my-tickets');
      }
    } catch (error) {
      toast.error('Failed to load ticket');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTicket();
  }, [id]);

  const simulateAIResponse = () => {
    setAiLoading(true);
    setTimeout(() => {
      if (ticket) {
        const categories = ['Billing', 'Technical', 'Account', 'Feature Request', 'Bug Report'];
        const suggestions = [
          "Try clearing your browser cache and cookies, then try again.",
          "Please check if you are using the correct login credentials.",
          "This issue has been reported by other users and a fix is in progress.",
          "We recommend updating to the latest version of our product.",
          "Our team will get back to you within 2 business hours.",
        ];
        
        const updatedTicket = {
          ...ticket,
          category: categories[Math.floor(Math.random() * categories.length)],
          ai_suggestion: suggestions[Math.floor(Math.random() * suggestions.length)],
        };
        
        setTicket(updatedTicket);
        toast.success('AI analysis completed');
      }
      setAiLoading(false);
    }, 1250);
  };

  const updateStatus = async (newStatus: 'Open' | 'In Progress' | 'Resolved') => {
    if (!ticket || !id) return;
    
    try {
      await ticketsAPI.updateTicket(parseInt(id), { status: newStatus });
      setTicket({ ...ticket, status: newStatus });
      toast.success(`Status updated to ${newStatus}`);
    } catch (err) {
      toast.error('Could not update status');
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-violet-600"></div>
      </div>
    );
  }

  if (!ticket) return null;

  return (
    <div className="max-w-4xl mx-auto p-8 pt-24">
      <button 
        onClick={() => navigate(-1)}
        className="flex items-center text-sm text-slate-500 hover:text-slate-700 mb-8"
      >
        <ArrowLeft className="mr-1.5 w-4 h-4" /> Back to tickets
      </button>

      <div className="flex justify-between items-start mb-8">
        <div>
          <div className="flex items-center gap-4">
            <StatusBadge status={ticket.status} />
            <div className="text-xs font-mono text-slate-400">TKT-{String(ticket.id).padStart(4, '0')}</div>
          </div>
          <h1 className="text-4xl font-semibold tracking-tight mt-3 pr-12">{ticket.title}</h1>
        </div>
        
        <div className="text-right">
          <div className="text-xs text-slate-500">CREATED</div>
          <div className="text-sm mt-1">{new Date(ticket.created_at).toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })}</div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        <div className="lg:col-span-7 space-y-6">
          <Card title="Issue Description">
            <div className="prose text-slate-600 dark:text-slate-300 leading-relaxed">
              {ticket.description}
            </div>
          </Card>

          {ticket.ai_suggestion && (
            <Card title="💡 AI Response Suggestion">
              <div className="bg-violet-50 dark:bg-slate-900 border border-violet-100 dark:border-slate-700 p-6 rounded-2xl text-slate-700 dark:text-slate-300">
                {ticket.ai_suggestion}
              </div>
              <div className="text-[10px] text-violet-400 flex items-center gap-2 mt-4">
                <Sparkles className="w-3 h-3" /> GENERATED BY AI
              </div>
            </Card>
          )}
        </div>

        <div className="lg:col-span-5 space-y-6">
          <Card title="Ticket Information">
            <div className="space-y-6">
              <div>
                <div className="text-xs uppercase text-slate-400 mb-2 tracking-widest">CURRENT STATUS</div>
                <div className="flex gap-3">
                  {(['Open', 'In Progress', 'Resolved'] as const).map((s) => (
                    <button
                      key={s}
                      onClick={() => updateStatus(s)}
                      className={`text-xs px-5 py-2 rounded-3xl transition-all border ${
                        ticket.status === s 
                          ? 'bg-slate-900 text-white border-slate-900' 
                          : 'hover:bg-slate-100 border-slate-200'
                      }`}
                    >
                      {s}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <div className="text-xs uppercase text-slate-400 mb-3 tracking-widest">AI CATEGORY</div>
                <div className="inline-flex items-center gap-2 px-6 py-2 bg-white dark:bg-slate-900 border border-slate-200 rounded-3xl text-sm">
                  {ticket.category ? (
                    <span className="font-medium">{ticket.category}</span>
                  ) : (
                    <button 
                      onClick={simulateAIResponse}
                      disabled={aiLoading}
                      className="flex items-center gap-2 text-violet-600 hover:text-violet-700 disabled:opacity-70"
                    >
                      <Sparkles className="w-4 h-4" />
                      {aiLoading ? 'Analyzing...' : 'Run AI Categorization'}
                    </button>
                  )}
                </div>
              </div>

              <div className="pt-4 border-t text-xs">
                <div className="flex justify-between py-2">
                  <span className="text-slate-500">Last Updated</span>
                  <span>{new Date(ticket.updated_at).toLocaleString()}</span>
                </div>
                <div className="flex justify-between py-2">
                  <span className="text-slate-500">Submitted By</span>
                  <span>You</span>
                </div>
              </div>
            </div>
          </Card>

          <Card title="Need more help?">
            <p className="text-sm text-slate-500">Our support team is available 24/7.</p>
            <Button variant="outline" className="mt-6 w-full">Contact Human Agent</Button>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default TicketDetail;